export default [
  {
    name: "Noise Cancelling Headphones",
    price: 4999,
    description: "High-quality noise cancelling over-ear headphones.",
    ratings: 4.5,
    images: {
      public_id: "sample_image_1",
      url: "https://example.com/image1.jpg",
    },
    category: "Headphones",
    seller: "Tech World",
    numOfReviews: 1,
    reviews: {
      user: "60d0fe4f5311236168a109ca",
      rating: 4,
      comment: "Great sound quality!",
    },
    user: "60d0fe4f5311236168a109ca",
  },
  {
    name: "4K UHD Smart TV",
    price: 29999,
    description: "A 55-inch Ultra HD smart TV with voice control.",
    ratings: 4.7,
    images: {
      public_id: "sample_image_2",
      url: "https://example.com/image2.jpg",
    },
    category: "Electronics",
    seller: "Home Appliances Ltd",
    numOfReviews: 0,
    user: "60d0fe4f5311236168a109cb",
  },
  {
    name: "Wireless Bluetooth Speaker",
    price: 1999,
    description: "Portable Bluetooth speaker with deep bass and 10h battery life.",
    ratings: 4.3,
    images: {
      public_id: "sample_image_3",
      url: "https://example.com/image3.jpg",
    },
    category: "Accessories",
    seller: "MusicMania",
    numOfReviews: 1,
    reviews: {
      user: "60d0fe4f5311236168a109cc",
      rating: 5,
      comment: "Amazing sound for the price!",
    },
    user: "60d0fe4f5311236168a109cc",
  },
  {
    name: "Gaming Laptop",
    price: 75999,
    description: "High-performance gaming laptop with RTX 3060 GPU.",
    ratings: 4.8,
    images: {
      public_id: "sample_image_4",
      url: "https://example.com/image4.jpg",
    },
    category: "Laptops",
    seller: "GameHub",
    numOfReviews: 2,
    reviews: {
      user: "60d0fe4f5311236168a109cd",
      rating: 4,
      comment: "Runs all modern games smoothly.",
    },
    user: "60d0fe4f5311236168a109cd",
  },
  {
    name: "Smart Fitness Watch",
    price: 7999,
    description: "Track your activity and health with this stylish smartwatch.",
    ratings: 4.2,
    images: {
      public_id: "sample_image_5",
      url: "https://example.com/image5.jpg",
    },
    category: "Accessories",
    seller: "FitTech",
    numOfReviews: 3,
    reviews: {
      user: "60d0fe4f5311236168a109ce",
      rating: 4,
      comment: "Good features and battery life.",
    },
    user: "60d0fe4f5311236168a109ce",
  },
  {
    name: "DSLR Camera",
    price: 45999,
    description: "24MP DSLR with 18-55mm lens kit for stunning photography.",
    ratings: 4.6,
    images: {
      public_id: "sample_image_6",
      url: "https://example.com/image6.jpg",
    },
    category: "Cameras",
    seller: "PhotoPro",
    numOfReviews: 5,
    reviews: {
      user: "60d0fe4f5311236168a109cf",
      rating: 5,
      comment: "Excellent image quality and easy to use.",
    },
    user: "60d0fe4f5311236168a109cf",
  },
  {
    name: "Ergonomic Office Chair",
    price: 12999,
    description: "Comfortable office chair with adjustable height and lumbar support.",
    ratings: 4.1,
    images: {
      public_id: "sample_image_7",
      url: "https://example.com/image7.jpg",
    },
    category: "Home",
    seller: "ComfortPlus",
    numOfReviews: 4,
    reviews: {
      user: "60d0fe4f5311236168a109d0",
      rating: 4,
      comment: "Great comfort for long working hours.",
    },
    user: "60d0fe4f5311236168a109d0",
  },
  {
    name: "Electric Kettle",
    price: 2999,
    description: "1.7L electric kettle with auto shut-off and boil dry protection.",
    ratings: 4.0,
    images: {
      public_id: "sample_image_8",
      url: "https://example.com/image8.jpg",
    },
    category: "Home",
    seller: "Home Essentials",
    numOfReviews: 2,
    reviews: {
      user: "60d0fe4f5311236168a109d1",
      rating: 3,
      comment: "Heats quickly but a bit noisy.",
    },
    user: "60d0fe4f5311236168a109d1",
  },
  {
    name: "Organic Almonds",
    price: 899,
    description: "Fresh and organic almonds, 500g pack.",
    ratings: 4.4,
    images: {
      public_id: "sample_image_9",
      url: "https://example.com/image9.jpg",
    },
    category: "Food",
    seller: "Healthy Harvest",
    numOfReviews: 10,
    reviews: {
      user: "60d0fe4f5311236168a109d2",
      rating: 5,
      comment: "Crunchy and delicious!",
    },
    user: "60d0fe4f5311236168a109d2",
  },
  {
    name: "Yoga Mat",
    price: 1599,
    description: "Non-slip yoga mat for all types of workouts.",
    ratings: 4.3,
    images: {
      public_id: "sample_image_10",
      url: "https://example.com/image10.jpg",
    },
    category: "Sports",
    seller: "FitLife",
    numOfReviews: 6,
    reviews: {
      user: "60d0fe4f5311236168a109d3",
      rating: 4,
      comment: "Good grip and cushioning.",
    },
    user: "60d0fe4f5311236168a109d3",
  },
  {
    name: "Camping Tent",
    price: 12999,
    description: "4-person waterproof camping tent with easy setup.",
    ratings: 4.5,
    images: {
      public_id: "sample_image_11",
      url: "https://example.com/image11.jpg",
    },
    category: "Outdoor",
    seller: "Adventure Gear",
    numOfReviews: 3,
    reviews: {
      user: "60d0fe4f5311236168a109d4",
      rating: 5,
      comment: "Perfect for weekend trips!",
    },
    user: "60d0fe4f5311236168a109d4",
  },
];